"""table publication

Revision ID: 8dd29ec5076d
Revises: 894eb8dd741f
Create Date: 2020-09-08 22:59:53.089698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd29ec5076d'
down_revision = '894eb8dd741f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corps', sa.String(length=140), nullable=True),
    sa.Column('horodatage', sa.DateTime(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_horodatage'), 'publication', ['horodatage'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_horodatage'), table_name='publication')
    op.drop_table('publication')
    # ### end Alembic commands ###
