"""dernier acces

Revision ID: db0092c9485d
Revises: f13c38d471ae
Create Date: 2020-09-28 14:15:36.007835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0092c9485d'
down_revision = 'f13c38d471ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('dernier_acces', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'dernier_acces')
    # ### end Alembic commands ###
