"""avatar

Revision ID: f13c38d471ae
Revises: 8dd29ec5076d
Create Date: 2020-09-14 15:19:03.586359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13c38d471ae'
down_revision = '8dd29ec5076d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateur', sa.Column('a_propos_de_moi', sa.String(length=140), nullable=True))
    op.add_column('utilisateur', sa.Column('avatar', sa.Text(length=131072), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'avatar')
    op.drop_column('utilisateur', 'a_propos_de_moi')
    # ### end Alembic commands ###
